#5823: Fix query: Select distinct cases
- Added Case.changeDate to avoid query failure:
JdbcSQLSyntaxErrorException: Order by expression "case0_.changedate"
must be in the result list in this case